// VeniceAI.ts

import { IServiceProvider } from './types';

export default {
  name: 'VeniceAI',
  apiBase: 'https://api.venice.ai/api/v1',
  currency: 'USD',
  options: {
    apiBaseCustomizable: false,
    apiKeyCustomizable: true,
  },
  chat: {
    apiSchema: ['base', 'key', 'model'],
    presencePenalty: { min: -2, max: 2, default: 0 },
    topP: { min: 0, max: 1, default: 0.9 },
    temperature: { min: 0, max: 1, default: 0.8 },
    models: {
      'llama-3.3-70b': {
        label: 'Llama 3.3 70b',
        contextWindow: 65536,
        description:
          'Default model. Function calling enabled. Supports web search.',
        capabilities: {
          optimizedForCode: false,
          supportsVision: false,
          supportsFunctionCalling: true,
          supportsResponseSchema: false,
          supportsWebSearch: true,
          supportsReasoning: false,
        },
        constraints: {
          temperature: { default: 0.8 },
          top_p: { default: 0.9 },
        },
        modelSource: 'https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct',
        created: 1733768349,
        owned_by: 'venice.ai',
        offline: false,
        traits: ['function_calling_default', 'default'],
        type: 'text',
        object: 'model',
      },
      'llama-3.2-3b': {
        label: 'Llama 3.2 3b',
        contextWindow: 131072,
        description:
          'Fastest model available. Supports function calling and response schema.',
        capabilities: {
          optimizedForCode: false,
          supportsVision: false,
          supportsFunctionCalling: true,
          supportsResponseSchema: true,
          supportsWebSearch: false,
          supportsReasoning: false,
        },
        constraints: {
          temperature: { default: 0.8 },
          top_p: { default: 0.9 },
        },
        modelSource: 'https://huggingface.co/meta-llama/Llama-3.2-3B',
        created: 1727966436,
        owned_by: 'venice.ai',
        offline: false,
        traits: ['fastest'],
        type: 'text',
        object: 'model',
      },
      'mistral-31-24b': {
        label: 'Mistral 31 24b',
        contextWindow: 131072,
        description:
          'Default vision model. Supports function calling, response schema, and web search.',
        capabilities: {
          optimizedForCode: false,
          supportsVision: true,
          supportsFunctionCalling: true,
          supportsResponseSchema: true,
          supportsWebSearch: true,
          supportsReasoning: false,
        },
        constraints: {
          temperature: { default: 0.15 },
          top_p: { default: 0.9 },
        },
        modelSource:
          'https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503',
        created: 1742262554,
        owned_by: 'venice.ai',
        offline: false,
        traits: ['default_vision'],
        type: 'text',
        object: 'model',
      },
      'qwen-2.5-qwq-32b': {
        label: 'Qwen 2.5 Qwq 32b',
        contextWindow: 32768,
        description:
          'Optimized for code. Supports response schema, web search, and reasoning.',
        capabilities: {
          optimizedForCode: true,
          supportsVision: false,
          supportsFunctionCalling: false,
          supportsResponseSchema: true,
          supportsWebSearch: true,
          supportsReasoning: true,
        },
        constraints: {
          temperature: { default: 0.6 },
          top_p: { default: 0.95 },
        },
        modelSource: 'https://huggingface.co/Qwen/QwQ-32B',
        created: 1741218077,
        owned_by: 'venice.ai',
        offline: false,
        traits: [],
        type: 'text',
        object: 'model',
      },
      'qwen-2.5-vl': {
        label: 'Qwen 2.5 Vl',
        contextWindow: 32768,
        description: 'Supports vision and web search.',
        capabilities: {
          optimizedForCode: false,
          supportsVision: true,
          supportsFunctionCalling: false,
          supportsResponseSchema: false,
          supportsWebSearch: true,
          supportsReasoning: false,
        },
        constraints: {
          temperature: { default: 0.8 },
          top_p: { default: 0.9 },
        },
        modelSource: 'https://huggingface.co/Qwen/Qwen2.5-VL-72B-Instruct',
        created: 1739074852,
        owned_by: 'venice.ai',
        offline: false,
        traits: [],
        type: 'text',
        object: 'model',
      },
      'dolphin-2.9.2-qwen2-72b': {
        label: 'Dolphin 2.9.2 Qwen2 72b',
        contextWindow: 32768,
        description:
          'Most uncensored model. Supports response schema and web search.',
        capabilities: {
          optimizedForCode: false,
          supportsVision: false,
          supportsFunctionCalling: false,
          supportsResponseSchema: true,
          supportsWebSearch: true,
          supportsReasoning: false,
        },
        constraints: {
          temperature: { default: 0.5 },
          top_p: { default: 1 },
        },
        modelSource:
          'https://huggingface.co/cognitivecomputations/dolphin-2.9.2-qwen2-72b',
        created: 1726869022,
        owned_by: 'venice.ai',
        offline: false,
        traits: ['most_uncensored'],
        type: 'text',
        object: 'model',
      },
      'llama-3.1-405b': {
        label: 'Llama 3.1 405b',
        contextWindow: 65536,
        description: 'Most intelligent model. Supports web search.',
        capabilities: {
          optimizedForCode: false,
          supportsVision: false,
          supportsFunctionCalling: false,
          supportsResponseSchema: false,
          supportsWebSearch: true,
          supportsReasoning: false,
        },
        constraints: {
          temperature: { default: 0.8 },
          top_p: { default: 0.9 },
        },
        modelSource:
          'https://huggingface.co/meta-llama/Meta-Llama-3.1-405B-Instruct',
        created: 1730396371,
        owned_by: 'venice.ai',
        offline: false,
        traits: ['most_intelligent'],
        type: 'text',
        object: 'model',
      },
      'deepseek-r1-671b': {
        label: 'Deepseek R1 671b',
        contextWindow: 131072,
        description:
          'Default reasoning model. Optimized for code. Supports web search.',
        capabilities: {
          optimizedForCode: true,
          supportsVision: false,
          supportsFunctionCalling: false,
          supportsResponseSchema: false,
          supportsWebSearch: true,
          supportsReasoning: true,
        },
        constraints: {
          temperature: { default: 0.6 },
          top_p: { default: 0.9 },
        },
        modelSource: 'https://huggingface.co/deepseek-ai/DeepSeek-R1',
        created: 1738690625,
        owned_by: 'venice.ai',
        offline: false,
        traits: ['default_reasoning'],
        type: 'text',
        object: 'model',
      },
      'qwen-2.5-coder-32b': {
        label: 'Qwen 2.5 Coder 32b',
        contextWindow: 32768,
        description: 'Default code model. Optimized for code.',
        capabilities: {
          optimizedForCode: true,
          supportsVision: false,
          supportsFunctionCalling: false,
          supportsResponseSchema: false,
          supportsWebSearch: false,
          supportsReasoning: false,
        },
        constraints: {
          temperature: { default: 0.8 },
          top_p: { default: 0.9 },
        },
        modelSource:
          'https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct-GGUF',
        created: 1731628653,
        owned_by: 'venice.ai',
        offline: false,
        traits: ['default_code'],
        type: 'text',
        object: 'model',
      },
      'deepseek-coder-v2-lite': {
        label: 'Deepseek Coder V2 Lite',
        contextWindow: 131072,
        description: 'Optimized for code. Supports response schema.',
        capabilities: {
          optimizedForCode: true,
          supportsVision: false,
          supportsFunctionCalling: false,
          supportsResponseSchema: true,
          supportsWebSearch: false,
          supportsReasoning: false,
        },
        constraints: {
          temperature: { default: 0.8 },
          top_p: { default: 0.9 },
        },
        modelSource:
          'https://huggingface.co/deepseek-ai/deepseek-coder-v2-lite-Instruct',
        created: 1740253117,
        owned_by: 'venice.ai',
        offline: false,
        traits: [],
        type: 'text',
        object: 'model',
      },
    },
  },
};
